# Alacritty configuration - Zyphlen Kotani

import = [
    "~/.config/alacritty/themes/themes/vesper.toml",
    "~/.config/alacritty/keybindings.toml"
]

#working_directory = "~"
live_config_reload = true

[window]
dimensions.columns = 125
dimensions.lines = 40
#padding.x = 10
#padding.y = 10
dynamic_padding = true
decorations = "Full"
opacity = 0.90
startup_mode = "Windowed"
title = "terminal"

[scrolling]
history = 50000

[font]
normal.family = "MartianMono NF"
bold.family = "MartianMono NF"
italic.family = "MartianMono NF"
bold_italic.family = "MartianMono NF"
size = 9.0

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Underline"
style.blinking = "Always"
blink_interval = 500
blink_timeout = 0
thickness = 0.0
